//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Appointment_management_system_integration.SmsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FetchdeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendsmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendsmssmrdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Appointment_management_system_integration.Properties.Settings.Default.Appointment_management_system_integration_SmsService_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchdeliveryCompletedEventHandler FetchdeliveryCompleted;
        
        /// <remarks/>
        public event sendsmsCompletedEventHandler sendsmsCompleted;
        
        /// <remarks/>
        public event sendsmssmrdCompletedEventHandler sendsmssmrdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fetchdelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fetchdelivery(string id) {
            object[] results = this.Invoke("Fetchdelivery", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FetchdeliveryAsync(string id) {
            this.FetchdeliveryAsync(id, null);
        }
        
        /// <remarks/>
        public void FetchdeliveryAsync(string id, object userState) {
            if ((this.FetchdeliveryOperationCompleted == null)) {
                this.FetchdeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchdeliveryOperationCompleted);
            }
            this.InvokeAsync("Fetchdelivery", new object[] {
                        id}, this.FetchdeliveryOperationCompleted, userState);
        }
        
        private void OnFetchdeliveryOperationCompleted(object arg) {
            if ((this.FetchdeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchdeliveryCompleted(this, new FetchdeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendsms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendsms(string mobileno, string messagetext, string SenderId) {
            object[] results = this.Invoke("sendsms", new object[] {
                        mobileno,
                        messagetext,
                        SenderId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendsmsAsync(string mobileno, string messagetext, string SenderId) {
            this.sendsmsAsync(mobileno, messagetext, SenderId, null);
        }
        
        /// <remarks/>
        public void sendsmsAsync(string mobileno, string messagetext, string SenderId, object userState) {
            if ((this.sendsmsOperationCompleted == null)) {
                this.sendsmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendsmsOperationCompleted);
            }
            this.InvokeAsync("sendsms", new object[] {
                        mobileno,
                        messagetext,
                        SenderId}, this.sendsmsOperationCompleted, userState);
        }
        
        private void OnsendsmsOperationCompleted(object arg) {
            if ((this.sendsmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendsmsCompleted(this, new sendsmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendsmssmrd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendsmssmrd(string mobileno, string messagetext, string SenderId, string SAPID) {
            object[] results = this.Invoke("sendsmssmrd", new object[] {
                        mobileno,
                        messagetext,
                        SenderId,
                        SAPID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendsmssmrdAsync(string mobileno, string messagetext, string SenderId, string SAPID) {
            this.sendsmssmrdAsync(mobileno, messagetext, SenderId, SAPID, null);
        }
        
        /// <remarks/>
        public void sendsmssmrdAsync(string mobileno, string messagetext, string SenderId, string SAPID, object userState) {
            if ((this.sendsmssmrdOperationCompleted == null)) {
                this.sendsmssmrdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendsmssmrdOperationCompleted);
            }
            this.InvokeAsync("sendsmssmrd", new object[] {
                        mobileno,
                        messagetext,
                        SenderId,
                        SAPID}, this.sendsmssmrdOperationCompleted, userState);
        }
        
        private void OnsendsmssmrdOperationCompleted(object arg) {
            if ((this.sendsmssmrdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendsmssmrdCompleted(this, new sendsmssmrdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FetchdeliveryCompletedEventHandler(object sender, FetchdeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchdeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchdeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendsmsCompletedEventHandler(object sender, sendsmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendsmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendsmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendsmssmrdCompletedEventHandler(object sender, sendsmssmrdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendsmssmrdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendsmssmrdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591